### Python modules
- Module Creation and Usage
- Advanced Modules and Packages
    - numpy
    - pandas
    - matplotlib

In [1]:
# Creation of Used Module
import mymodule
mymodule.say_hi()
tot = mymodule.add(10, 20)
print(tot)
print(mymodule.name)
print(mymodule.pi)

Hello Python
30
Vinay
3.14


In [2]:
import mymodule as f
f.say_hi()

Hello Python


In [3]:
from mymodule import *
f.say_hi()

Hello Python


In [4]:
dir(f)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'add',
 'name',
 'pi',
 'say_hi']

In [12]:
print(say_hi.__doc__)

Hai Function


In [9]:
import mymodule1
mymodule1.bye()
mymodule1.hello()

Good Bye
Hello


### numerical Python
- Homogeneous operations
- All mathematical functions we use numpy package (third party)

In [54]:
import numpy as np
a = np.array([2, 4, 6, 8], dtype = np.int8) # List Array
print(type(a))

<class 'numpy.ndarray'>


In [57]:
# Attributes of a ndarray
print(a.ndim) # no. of dimensions
print(a.shape) # no. of elements and columns
print(a.size) # number of elements
print(a.itemsize)   # bytes required to store
print(a.dtype) # datatype

1
(4,)
4
4
int32


In [58]:
import numpy as np  # Tuple Array
a = np.array((2, 4, 6, 8))
print(type(a))

<class 'numpy.ndarray'>


In [59]:
# Attributes of a ndarray
print(a.ndim) # no. of dimensions
print(a.shape) # no. of elements and columns
print(a.size) # number of elements
print(a.itemsize)   # bytes required to store
print(a.dtype) # datatype

1
(4,)
4
4
int32


In [71]:
# Add 5 to all Elements of List
l = np.array([2, 3, 4, 5])
l = l + 5
print(l)
l

[ 7  8  9 10]


array([ 7,  8,  9, 10])

In [68]:
l = [1, 2, 3, 4, 5]
print(l)
l = list(map(lambda x: x+5, l))
print(l)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


In [81]:
m = np.array([2, 3, 4, 5])
n = np.array([6, 7, 8, 9])
print(m + n)
m + n

[ 8 10 12 14]


array([ 8, 10, 12, 14])

In [78]:
m = np.array([2, 3, 4, 5])
n = np.array([6, 7, 8, 9])
print(m ** n)
m ** n

[     64    2187   65536 1953125]


array([     64,    2187,   65536, 1953125], dtype=int32)

In [90]:
import time
values = list(range(1000000))
s = time.time()
lvalues = [i**2 for i in values]  # list comprehension
e = time.time()
print(e-s)
avalues = np.array(values)
s = time.time()
avalues = avalues ** 2
e= time.time()
print(e-s)

0.34773921966552734
0.0
